export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/registration'
export const ADMIN_ROUTE = '/admin'
export const SHOP_ROUTE = '/'
export const DEVICE_ROUTE = '/device'
export const BASKET_ROUTE = '/basket'
